/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { alignmentType } from "./components/dlk-content/dlk-content";
import { textType } from "./components/dlk-text/dlk-text";
import { titleType } from "./components/dlk-title/dlk-title";
export { alignmentType } from "./components/dlk-content/dlk-content";
export { textType } from "./components/dlk-text/dlk-text";
export { titleType } from "./components/dlk-title/dlk-title";
export namespace Components {
    interface DlkButton {
    }
    interface DlkContent {
        "alignment": alignmentType;
        "preTitle": string;
        "title": string;
    }
    interface DlkList {
    }
    interface DlkListItem {
    }
    interface DlkText {
        "type": textType;
    }
    interface DlkTitle {
        "titleType": titleType;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDlkButtonElement extends Components.DlkButton, HTMLStencilElement {
    }
    var HTMLDlkButtonElement: {
        prototype: HTMLDlkButtonElement;
        new (): HTMLDlkButtonElement;
    };
    interface HTMLDlkContentElement extends Components.DlkContent, HTMLStencilElement {
    }
    var HTMLDlkContentElement: {
        prototype: HTMLDlkContentElement;
        new (): HTMLDlkContentElement;
    };
    interface HTMLDlkListElement extends Components.DlkList, HTMLStencilElement {
    }
    var HTMLDlkListElement: {
        prototype: HTMLDlkListElement;
        new (): HTMLDlkListElement;
    };
    interface HTMLDlkListItemElement extends Components.DlkListItem, HTMLStencilElement {
    }
    var HTMLDlkListItemElement: {
        prototype: HTMLDlkListItemElement;
        new (): HTMLDlkListItemElement;
    };
    interface HTMLDlkTextElement extends Components.DlkText, HTMLStencilElement {
    }
    var HTMLDlkTextElement: {
        prototype: HTMLDlkTextElement;
        new (): HTMLDlkTextElement;
    };
    interface HTMLDlkTitleElement extends Components.DlkTitle, HTMLStencilElement {
    }
    var HTMLDlkTitleElement: {
        prototype: HTMLDlkTitleElement;
        new (): HTMLDlkTitleElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "dlk-button": HTMLDlkButtonElement;
        "dlk-content": HTMLDlkContentElement;
        "dlk-list": HTMLDlkListElement;
        "dlk-list-item": HTMLDlkListItemElement;
        "dlk-text": HTMLDlkTextElement;
        "dlk-title": HTMLDlkTitleElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DlkButton {
    }
    interface DlkContent {
        "alignment"?: alignmentType;
        "preTitle"?: string;
        "title"?: string;
    }
    interface DlkList {
    }
    interface DlkListItem {
    }
    interface DlkText {
        "type"?: textType;
    }
    interface DlkTitle {
        "titleType"?: titleType;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "dlk-button": DlkButton;
        "dlk-content": DlkContent;
        "dlk-list": DlkList;
        "dlk-list-item": DlkListItem;
        "dlk-text": DlkText;
        "dlk-title": DlkTitle;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dlk-button": LocalJSX.DlkButton & JSXBase.HTMLAttributes<HTMLDlkButtonElement>;
            "dlk-content": LocalJSX.DlkContent & JSXBase.HTMLAttributes<HTMLDlkContentElement>;
            "dlk-list": LocalJSX.DlkList & JSXBase.HTMLAttributes<HTMLDlkListElement>;
            "dlk-list-item": LocalJSX.DlkListItem & JSXBase.HTMLAttributes<HTMLDlkListItemElement>;
            "dlk-text": LocalJSX.DlkText & JSXBase.HTMLAttributes<HTMLDlkTextElement>;
            "dlk-title": LocalJSX.DlkTitle & JSXBase.HTMLAttributes<HTMLDlkTitleElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
